'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, CircleDollarSign, Plus, Search } from 'lucide-react';
import Modal from '@/components/Modal';
import PageHeader from '@/components/PageHeader';
import { EmptyState, ErrorState, LoadingState } from '@/components/ContentState';
import { api, getAllPages, getApiError } from '@/lib/api';
import { formatCurrency, formatDate } from '@/lib/format';
import type { ProductionCost, ProductionOrder, ProductionPayment } from '@/types';

type PayableCost = ProductionCost & { orderId: string; orderNumber: string };
const METHODS = [['cash', 'Cash'], ['bank_transfer', 'Bank transfer'], ['upi', 'UPI'], ['cheque', 'Cheque'], ['other', 'Other']] as const;
const today = () => new Date().toISOString().slice(0, 10);

export default function PaymentOutRegister() {
  const [rows, setRows] = useState<ProductionPayment[]>([]); const [costs, setCosts] = useState<PayableCost[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [paymentRes, orderRes] = await Promise.all([getAllPages<ProductionPayment>('/production-orders/payments/register'), getAllPages<ProductionOrder>('/production-orders')]); setRows(paymentRes.data); setCosts(orderRes.data.flatMap((order) => order.costs.filter((cost) => Number(cost.amount) > Number(cost.paidAmount)).map((cost) => ({ ...cost, orderId: order.id, orderNumber: order.orderNumber })))); } catch (loadError) { setError(getApiError(loadError, 'Could not load payment-out records.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return term ? rows.filter(({ cost, method, reference }) => [cost.description, cost.order.orderNumber, cost.supplier?.name, method, reference].some((value) => value?.toLowerCase().includes(term))) : rows; }, [query, rows]);
  const total = rows.reduce((sum, row) => sum + Number(row.amount), 0);
  return <><PageHeader title="Payment Out" description="Record and review payments made for production costs and suppliers." action={<button type="button" onClick={() => setOpen(true)} className="btn-primary inline-flex items-center gap-2"><Plus size={16} />Record payment</button>} /><div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-3"><Metric label="Payments" value={rows.length.toLocaleString('en-IN')} /><Metric label="Outstanding costs" value={costs.length.toLocaleString('en-IN')} /><Metric label="Total paid" value={formatCurrency(total)} wide /></div><section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-bold text-slate-900">Payment Out register</h2><p className="mt-0.5 text-[10px] text-slate-400">Company and branch-specific outgoing payments</p></div><div className="relative w-full sm:w-80"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input aria-label="Search payment out" className="input-field pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Supplier, project, method, reference..." /></div></div>{loading ? <LoadingState label="Loading payments..." /> : error ? <ErrorState message={error} onRetry={load} /> : filtered.length === 0 ? <EmptyState icon={CircleDollarSign} title="No outgoing payments" description={query ? 'Try a different search.' : 'Record a payment against an outstanding production cost.'} /> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Project</th><th className="px-5 py-3">Description</th><th className="px-5 py-3">Supplier</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Reference</th><th className="px-5 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-3.5 text-slate-500">{formatDate(row.paidAt)}</td><td className="px-5 py-3.5 font-bold text-blue-700">{row.cost.order.orderNumber}</td><td className="px-5 py-3.5 font-semibold text-slate-700">{row.cost.description}</td><td className="px-5 py-3.5 text-slate-600">{row.cost.supplier?.name || 'Not assigned'}</td><td className="px-5 py-3.5 capitalize text-slate-600">{row.method.replaceAll('_', ' ')}</td><td className="px-5 py-3.5 text-slate-500">{row.reference || '—'}</td><td className="px-5 py-3.5 text-right font-bold text-red-600">{formatCurrency(row.amount)}</td></tr>)}</tbody></table></div>}</section>{open && <PaymentOutModal costs={costs} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); void load(); }} />}</>;
}

function PaymentOutModal({ costs, onClose, onSaved }: { costs: PayableCost[]; onClose: () => void; onSaved: () => void }) {
  const [costId, setCostId] = useState(''); const [amount, setAmount] = useState(''); const [method, setMethod] = useState('cash'); const [reference, setReference] = useState(''); const [paidAt, setPaidAt] = useState(today); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const selected = costs.find(({ id }) => id === costId); const outstanding = selected ? Number(selected.amount) - Number(selected.paidAmount) : 0;
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(''); try { await api.post(`/production-orders/${selected.orderId}/costs/${selected.id}/payments`, { amount: Number(amount), method, reference: reference.trim() || undefined, paidAt }); onSaved(); } catch (saveError) { setError(getApiError(saveError, 'Could not record payment.')); } finally { setSaving(false); } }
  return <Modal title="Record Payment Out" onClose={onClose} size="lg"><form onSubmit={submit} className="space-y-4">{error && <div role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700">{error}</div>}<label className="block"><span className="label">Outstanding cost *</span><select required className="input-field" value={costId} onChange={(e) => { const cost = costs.find(({ id }) => id === e.target.value); setCostId(e.target.value); setAmount(cost ? String(Number(cost.amount) - Number(cost.paidAmount)) : ''); }}><option value="">Select production cost</option>{costs.map((cost) => <option key={cost.id} value={cost.id}>{cost.orderNumber} · {cost.description} · Due {formatCurrency(Number(cost.amount) - Number(cost.paidAmount))}</option>)}</select></label>{selected && <div className="rounded-xl bg-red-50 p-3 text-xs text-red-800"><ArrowUpRight size={16} className="mb-1" />Outstanding: <strong>{formatCurrency(outstanding)}</strong></div>}<div className="grid gap-3 sm:grid-cols-2"><Field label="Amount *"><input required type="number" min="0.01" max={outstanding || undefined} step="0.01" className="input-field" value={amount} onChange={(e) => setAmount(e.target.value)} /></Field><Field label="Payment date *"><input required type="date" className="input-field" value={paidAt} onChange={(e) => setPaidAt(e.target.value)} /></Field><Field label="Payment method *"><select className="input-field" value={method} onChange={(e) => setMethod(e.target.value)}>{METHODS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Reference"><input className="input-field" value={reference} onChange={(e) => setReference(e.target.value)} placeholder="UTR, cheque no., note" /></Field></div><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button disabled={saving || !selected} className="btn-primary">{saving ? 'Saving...' : 'Save payment'}</button></div></form></Modal>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="label">{label}</span>{children}</label>; }
function Metric({ label, value, wide = false }: { label: string; value: string; wide?: boolean }) { return <div className={`card p-4 ${wide ? 'col-span-2 lg:col-span-1' : ''}`}><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1.5 text-xl font-extrabold text-slate-950">{value}</p></div>; }
